name: Update Sitemap and Deploy

on:
  push:
    branches:
      - main
    paths:
      - "data/komik.json"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install || echo "No dependencies"

      - name: Generate sitemap
        run: node update-sitemap.js

      - name: Commit and push sitemap
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add sitemap.xml
          git diff --cached --quiet || git commit -m "Update sitemap.xml"
          git push
